### ISSUE TITLE
Windows .exe not working

### ISSUE THREAD

**Issue by Ionix12** [bepaald/signalbackup-tools#28] opened 2021-03-04 00:05 UTC
Downloaded the Signalbackup-tools_win and attempted to run the .exe file to get the backup working. CMD flashes on the screen and then nothing happens. Please advise.

**Comment by gerega** [comment] 2021-03-04 17:12
The latest exe is defintely working. I have used it - and the one before - lately. You should search on the net on how to start / execute exe-files on commandline. Dont klick on the exe-file!

**Comment by bepaald** [comment] 2021-03-06 07:47
Yeah, exactly as @gerega says. Closing this assuming this is the issue, please feel free to open a new issue if there is anything else.

(probably duplicate of #18)

**Closed by bepaald** 2021-03-06 07:47 UTC
